// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cavhpbjrlrkyehmejkby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhdmhwYmpybHJreWVobWVqa2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzI3NDksImV4cCI6MjA2MjMwODc0OX0.ePb7aC2Vih2YonZNiEiRKKgFTTDLqTR-ALB16r5XA5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);